src/AdminSite/Controllers/SchedulerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Web;
using Marketplace.SaaS.Accelerator.DataAccess.Contracts;
using Marketplace.SaaS.Accelerator.DataAccess.Entities;
using Marketplace.SaaS.Accelerator.Services.Models;
using Marketplace.SaaS.Accelerator.Services.Services;
using Marketplace.SaaS.Accelerator.Services.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Marketplace.SaaS.Accelerator.AdminSite.Controllers;

/// <summary>
/// Scheduler Controller.
/// </summary>
/// <seealso cref="BaseController" />
[ServiceFilter(typeof(KnownUserAttribute))]
public class SchedulerController : BaseController
{
    /// <summary>
    /// The dimension repository
    /// </summary>
    private readonly IMeteredDimensionsRepository meteredRepository;

    /// <summary>
    /// logger controller
    /// </summary>
    private readonly SaaSClientLogger<SchedulerController> logger;

    /// <summary>
    /// the shceduler service
    /// </summary>
    private MeteredPlanSchedulerManagementService schedulerService;

    /// <summary>
    /// the subscription service
    /// </summary>
    private SubscriptionService subscriptionService;

    /// <summary>
    /// the user repository
    /// </summary>
    private readonly IUsersRepository usersRepository;

    /// <summary>
    /// Initializes a new instance of the <see cref="PlansController" /> class.
    /// </summary>
    /// <param name="subscriptionRepository">The subscription repository.</param>
    /// <param name="usersRepository">The users repository.</param>
    /// <param name="applicationConfigRepository">The application configuration repository.</param>
    /// <param name="plansRepository">The plans repository.</param>
    /// <param name="offerAttributeRepository">The offer attribute repository.</param>
    /// <param name="offerRepository">The offer repository.</param>
    /// <param name="logger">The logger.</param>
    public SchedulerController(ISubscriptionsRepository subscriptionRepository,
        IMeteredDimensionsRepository meteredRepository,
        ISchedulerFrequencyRepository frequencyRepository,
        IPlansRepository plansRepository,
        IMeteredPlanSchedulerManagementRepository schedulerRepository,
        ISchedulerManagerViewRepository schedulerViewRepository, 
        IUsersRepository usersRepository,
        SaaSClientLogger<SchedulerController> logger,
        ISubscriptionUsageLogsRepository subscriptionUsageLogsRepository,IApplicationConfigRepository applicationConfigRepository):base(applicationConfigRepository)

    {
        this.usersRepository = usersRepository;
        this.logger = logger;
        this.meteredRepository = meteredRepository;
        this.schedulerService = new MeteredPlanSchedulerManagementService(frequencyRepository, schedulerRepository, schedulerViewRepository,subscriptionUsageLogsRepository,applicationConfigRepository);
        this.subscriptionService = new SubscriptionService(subscriptionRepository,plansRepository);

    }

    /// <summary>
    /// Indexes this instance.
    /// </summary>
    /// <returns>return All subscription.</returns>
    public IActionResult Index()
    {
        this.logger.Info("Scheduler Controller / Get all data");
        try
        {
            List<SchedulerManagerViewModel> getAllSchedulerManagerViewData = new List<SchedulerManagerViewModel>();
            this.TempData["ShowWelcomeScreen"] = "True";
            var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);

            getAllSchedulerManagerViewData = this.schedulerService.GetAllSchedulerManagerList();

            return this.View(getAllSchedulerManagerViewData);
        }
        catch (Exception ex)
        {
            this.logger.LogError($"Message:{ex.Message} :: {ex.InnerException}");
            return this.View("Error", ex);
        }
    }

    public IActionResult NewScheduler(string subscriptionId, string dimId, string quantity)
    {
        this.logger.Info("New Scheduler Controller");
        try
        {
            SchedulerUsageViewModel schedulerUsageViewModel = new SchedulerUsageViewModel();

            this.TempData["ShowWelcomeScreen"] = "True";
            var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
            var allActiveMeteredSubscriptions = this.subscriptionService.GetActiveSubscriptionsWithMeteredPlan();
            List<SchedulerFrequencyModel> getAllEnabledFrequency = this.schedulerService.GetAllEnabledFrequency();

            // Create Frequency Dropdown list
            List<SelectListItem> SchedulerFrequencyList = new List<SelectListItem>();
            foreach (var item in getAllEnabledFrequency)
            {
                SchedulerFrequencyList.Add(new SelectListItem()
                {
                    Text = item.Frequency,
                    Value = item.Id.ToString(),
                });
            }

            // Create Subscription Dropdown list
            List<SelectListItem> SubscriptionList = new List<SelectListItem>();
            foreach (var item in allActiveMeteredSubscriptions)
            {
                SubscriptionList.Add(new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString(),
                });
            }
            // Create Plan Dropdown list
            List<SelectListItem> PlanList = new List<SelectListItem>();
            List<SelectListItem> DimensionsList = new List<SelectListItem>();

            schedulerUsageViewModel.DimensionsList = new SelectList(DimensionsList, "Value", "Text");
            schedulerUsageViewModel.SubscriptionList = new SelectList(SubscriptionList, "Value", "Text");
            schedulerUsageViewModel.SchedulerFrequencyList = new SelectList(SchedulerFrequencyList, "Value", "Text");


            schedulerUsageViewModel.SelectedSubscription = subscriptionId;
            schedulerUsageViewModel.Quantity = (Int32)Math.Round(Convert.ToDecimal(quantity), 0);

            if (!String.IsNullOrEmpty(dimId))
            {
                var dimensions = this.meteredRepository.Get().Where(d => d.Dimension == dimId).FirstOrDefault();
                if (dimensions != null)
                {
                    DimensionsList.Add(new SelectListItem()
                    {
                        Text = dimId,
                        Value = dimensions.Id.ToString(),
                        Selected = true
                    });
                    schedulerUsageViewModel.DimensionsList = new SelectList(DimensionsList, "Value", "Text");
                    schedulerUsageViewModel.SelectedDimension = dimensions.Id.ToString();
                }
            }
            else
            {
                if (subscriptionId != null)
                {
                    var selectSubscription = allActiveMeteredSubscriptions.Where(s => s.Id == int.Parse(subscriptionId)).FirstOrDefault();
                    if (selectSubscription != null)
                    {
                        // Create Dimension Dropdown list
                        List<MeteredDimensions> getAllDimensions = this.meteredRepository.GetDimensionsByPlanId(selectSubscription.AmpplanId);
                        if (getAllDimensions != null)
                        {

                            foreach (var item in getAllDimensions)
                            {
                                DimensionsList.Add(new SelectListItem()
                                {
                                    Text = item.Dimension,
                                    Value = item.Id.ToString(),
                                });
                            }
                        }
                    }
                }

            }
            return this.View(schedulerUsageViewModel);
        }
        catch (Exception ex)
        {
            this.logger.LogError($"Message:{ex.Message} :: {ex.InnerException}");
            return this.View("Error", ex);
        }
    }

    public IActionResult GetSubscriptionData(int id)
    {
        var allSubscriptionDetails = this.subscriptionService.GetActiveSubscriptionsWithMeteredPlan();
        var selectSubscription = allSubscriptionDetails.Where(s => s.Id == id).FirstOrDefault();
        if (selectSubscription != null)
        {
            // Create Dimension Dropdown list
            List<MeteredDimensions> getAllDimensions = this.meteredRepository.GetDimensionsByPlanId(selectSubscription.AmpplanId);
            if (getAllDimensions != null)
            {
                List<SelectListItem> selectedList = new List<SelectListItem>();
                foreach (var item in getAllDimensions)
                {
                    selectedList.Add(new SelectListItem()
                    {
                        Text = item.Dimension,
                        Value = item.Id.ToString(),
                    });
                }

                return Json(selectedList);

            }
            return this.PartialView("Error", "Can not find any metered dimension related to selected plan");

        }
        return this.PartialView("Error", "Subscription is Invalid");
    }

    public IActionResult AddNewScheduledTrigger(SchedulerUsageViewModel schedulerUsageViewModel)
    {
        try
        {
            var selectedDimension = this.meteredRepository.Get(int.Parse(schedulerUsageViewModel.SelectedDimension));
            MeteredPlanSchedulerManagementModel schedulerManagement = new MeteredPlanSchedulerManagementModel()
            {
                FrequencyId = Convert.ToInt32(schedulerUsageViewModel.SelectedSchedulerFrequency),
                SchedulerName = Convert.ToString(schedulerUsageViewModel.SchedulerName),

src/AdminSite/Views/Scheduler/Index.cshtml
@model List<Marketplace.SaaS.Accelerator.Services.Models.SchedulerManagerViewModel>
@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="">
    @if ((this.TempData["SupportMeteredBilling"] != null) && (this.TempData["SupportMeteredBilling"].ToString() == "1"))
    {
        <div class="">
            <div class="card-body text-center">
                <div>
                    <span class="cm-section-heading">Current Metered Plan Scheduled Trigger</span>

                </div>
                <div class="text-end">
                    <button type="submit" onclick="@("window.location.href='" + @Url.Action("NewScheduler", "Scheduler") + "'");" class="btn btn-secondary 
float-right cm-button-default">Add New Scheduled Metered Trigger</button>

                </div>
            </div>
            <div id="myModal">
                @if (Model != null && Model.Count() > 0)
                {
                    <br /><br />
                    <div class="alert alert-warning" role="alert">
                        Make sure to enable the frequecies you would like to run in the App Config!   
                    </div>

                    <div class="table-responsive mt20">
                        <b>Current UTC time: @DateTime.UtcNow; </b>  <br />
                        <table class="table table-bordered dt-responsive cm-table" width="90%" cellspacing="0">
                            <thead class="cm-table-head">
                                <tr>
                                    <th>Id</th>
                                    <th>Scheduler</th>
                                    <th>Subscription</th>
                                    <th>Customer</th>
                                    <th>Plan</th>
                                    <th>Dimension</th>
                                    <th>Quantity</th>
                                    <th>Frequency</th>
                                    <th>Start Date (UTC)</th>
                                    <th>Last Run (UTC)</th>
                                    <th>Next Run (UTC)</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    var i = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="text-left">
                                            @item.Id
                                        </td>
                                        <td class="text-left">
                                            @item.SchedulerName
                                        </td>
                                        <td class="text-left">
                                            @item.SubscriptionName
                                        </td>
                                        <td class="text-left">
                                            @item.PurchaserEmail
                                        </td>
                                        <td class="text-left">
                                            @item.PlanId
                                        </td>
                                        <td class="text-left">
                                            @item.Dimension
                                        </td>
                                        <td class="text-left">
                                            @item.Quantity
                                        </td>
                                        <td class="text-left">
                                            @item.Frequency
                                        </td>
                                        <td class="text-left">
                                            @item.StartDate
                                        </td>
                                        <td class="text-left">
                                            @item.LastRunTime
                                        </td>
                                        <td class="text-left">
                                            @item.NextRunTime
                                        </td>
                                        <td class="text-left cm-ellipsis">
                                            <div class="nav-item dropdown">
                                                <a class="nav-link dropdown cm-link-button" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                                    <a  class="dropdown-item cm-dropdown-option" href="Scheduler/DeleteSchedulerItem/@item.Id" onclick="return confirm('Are you sure?');" >Delete</a>
                                                    <a  class="dropdown-item cm-dropdown-option" href="Scheduler/SchedulerLogDetail/@item.Id">History</a>
                                                </div>
                                            </div>
                                        </td>

                                    </tr>
                                    i++;
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {

                    <div class="cm-panel-default mt40">
                        <div class="p-3 mr420">
                            <p>
                                You do not have any scheduled metered trigger yet!
                            </p>
                        </div>
                    </div>

                }
            </div>
        </div>
    }
    else
    {
        <div>
            <h1><span class="cm-section-heading"> Please activate Scheduler feature to access this section</span></h1>
        </div>
    }

</div>

src/AdminSite/Views/Scheduler/NewScheduler.cshtml
@model Marketplace.SaaS.Accelerator.Services.Models.SchedulerUsageViewModel
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
</head>
<body>

   <script type="text/javascript">
    $(function () {
        $("#SelectedSubscription").change(function () {
            var val = $(this).val();
            var subItems="";
            $.getJSON("@Url.Action("GetSubscriptionData","Scheduler")", {id:val} ,function (data) {
              $.each(data,function(index,item){
                subItems+="<option value='"+item.value+"'>"+item.text+"</option>"
              });
              $("#SelectedDimension").html(subItems);

            
            });
        });

        $("#btnSubmit").click(function () {
            var offset = new Date().getTimezoneOffset() / 60;
            document.getElementById("TimezoneOffset").value = offset;
        });

        $(document).ready(function() {
              var d =  new Date();
              d.setHours(d.getHours() + 1);
              var month = d.getMonth()+1;
              var day = d.getDate();
              var minutes = d.getMinutes();
              var hours=d.getHours();
              var output = d.getFullYear()+ '-' +
                          ((''+month).length<2 ? '0' : '') + month + '-' +
                           ((''+day).length<2 ? '0' : '') + day +'T'+
                           ((''+hours).length<2 ? '0' : '')+hours+':'+
                           ((''+minutes).length<2 ? '0' : '')+minutes;

              var date=document.getElementById("FirstRunDate")
              date.min=output
              $('#FirstRunDate').attr('min', output);
              $('#FirstRunDate').val(output);
              $('#FirstRunDate').attr('value',output);

          });
    });

</script>
@if ((this.TempData["SupportMeteredBilling"] != null) && (this.TempData["SupportMeteredBilling"].ToString() == "1"))
    {

        <div class="container">

            <div class="card-body">
                <div class="text-left">
                    <span class="cm-section-heading">Add New Scheduled Trigger for Metered Plan</span>
                </div>
            </div>


            <form method="post" id="frmSchedulerEvents" asp-action="AddNewScheduledTrigger" asp-controller="Scheduler" >
                <div style="align-content:center">
                    <table>
                        <tr>
                            <th colspan="2">
                                * Select a First Run Date at least an hour later than the current time.<br />
                                * To update an existing scheduler item, please use the same Name, Subscription id, Plan and Dimension.
                                <hr />
                                <br />
                            </th>
                        </tr>

                        <tr>
                            <th>Scheduler Name&nbsp;&nbsp;</th>
                            <th>@Html.TextBoxFor(s => s.SchedulerName, "",  new { @class = "form-control", required = "required" , pattern = @"^[a-zA-Z0-9-_]+$" })</th>
                        </tr>
                        <tr>
                            <th>Subscription</th>
                            <th>@Html.DropDownListFor(s => s.SelectedSubscription, Model.SubscriptionList, "-- Select Subscription --", new { @class = "form-control", required = "required"})</th>
                        </tr>
                        <tr>
                            <th>Dimension</th>
                            <th>@Html.DropDownListFor(s => s.SelectedDimension, Model.DimensionsList, "-- Select Dimension --", new { @class = "form-control", required = "required" })</th>
                        </tr>
                        <tr>
                            <th>Quantity</th>
                            <th><input asp-for="Quantity" type="number" class="form-control"  step="0.01" min="0.01" value="@Model.Quantity" required="true"></th>
                        </tr>

                        <tr>
                            <th>Frequency</th>
                            <th>@Html.DropDownListFor(s => s.SelectedSchedulerFrequency, Model.SchedulerFrequencyList, "-- Select Frequency --", new { @class = "form-control", required = "required" })</th>
                            @if (Model.SchedulerFrequencyList.Count() == 0)
                            {
                                <th>
                                    <span style="color:red">Please enable frequencies from the App Config, to allow the system to generate frequecies list. You can enable frequecies from <a href="/applicationconfig">here</a></span>
                                </th>
                            }
                        </tr>
                        <tr>
                            <th>First Run Date &nbsp;&nbsp; </th>
                            <th>  
                                <input asp-for="FirstRunDate" id="FirstRunDate" type="datetime-local" class="form-control"  required="true" size="24">
                            </th>
                            <th>Time will be rounded to nearest Hour</th>
                        </tr>

                        <tr>
                            <th></th>
                            <th>  

                                <br/>
                                <div class="input-group-append">
                                    <button type="submit" id="btnSubmit" class="btn btn-success">Add Scheduler Usage Task</button>
                                </div>
                            </th>
                            <th>  

                            </th>
                        </tr>

                    </table>
                </div>

                <input type="hidden" id="TimezoneOffset" name="TimezoneOffset" />

            </form>
        </div>
    }
    else
    {
    <div>
        <h1><span class="cm-section-heading"> Please activate Scheduler feature to access this section</span></h1>
    </div>
    }
</body>

src/AdminSite/Views/Scheduler/SchedulerLogDetail.cshtml
@*@using Microsoft.Marketplace.SaaS.SDK.Services.Models;*@
@model Marketplace.SaaS.Accelerator.Services.Models.SchedulerUsageViewModel
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
</head>
<body>
   <script type="text/javascript">
    
    // When the user clicks on <span> (x), close the modal
     function closeModel() {
      var modal = document.getElementById("detailModal");
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        var modal = document.getElementById("detailModal");
        modal.style.display = "none";
      }
    }

    function ShowDetail(request,response)
    {
        var detailModal = document.getElementById("detailModal");
        var requestJson = document.getElementById("requestJson");
        var responseJson = document.getElementById("responseJson");
        responseJson.textContent=response;
        requestJson.textContent=request;
        
        detailModal.style.display = "block";
    }
   </script>
 @if ((this.TempData["SupportMeteredBilling"] != null) && (this.TempData["SupportMeteredBilling"].ToString() == "1"))
    {
    <div class="card-body">
        <div class="modal-header header-bg">
            <h1><span class="cm-section-heading"> Activity Log</span></h1>
            <button type="submit"onclick="@("window.location.href='" + @Url.Action("index", "Scheduler") + "'");" class="cm-button-default text-right float-right">Back To Scheduler List</button>
        </div>
        <div class="modal-body">
            <div>
                <table class="table-bordered">
                    <tr>
                        <th>Subscription</th>
                        <td> @Html.DisplayFor(model => model.SelectedSubscription)</td>
                    </tr>
                    <tr>
                        <th>Dimension</th>
                        <td> @Html.DisplayFor(model => model.SelectedDimension)</td>
                    </tr>
                    <tr>
                        <th>Quantity</th>
                        <td> @Html.DisplayFor(model => model.Quantity)</td>
                    </tr>

                    <tr>
                        <th>Frequency</th>
                       <td> @Html.DisplayFor(model => model.SelectedSchedulerFrequency)</td>
                    </tr>
                    <tr>
                        <th>First Run Date (UTC)&nbsp;&nbsp; </th>
                        <td>  
                             @Html.DisplayFor(model => model.FirstRunDate)
                       </td>
                    </tr>

                    <tr>
                        <th>Next Run Date (UTC)&nbsp;&nbsp; </th>
                        <td>  
                             @Html.DisplayFor(model => model.NextRunDate)
                       </td>
                    </tr>

                </table>
                <br />
            </div>
            <p>
                This Log will show all the Meter events run manually or by any Scheduled Metered Trigger for this SaaS subscription.
            </p>

            <table class="table table-bordered dt-responsive cm-table" width=50%>
                <thead class="cm-table-head">
                    <tr>
                        <th width="10%">ID</th>
                        <th width="10%">Status</th>
                        <th width="10%">Submit Date</th>
                        <th width="10%">Run By</th>
                        <th width="10%"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var log in Model.MeteredAuditLogs)
                    {
                        <tr>

                            <td class="text-left">@log.Id</td>
                            <td class="text-left">@log.StatusCode</td>
                            <td class="text-left">
                                @if (log.CreatedDate != null && log.CreatedDate.HasValue)
                                {@log.CreatedDate.Value.ToString()}
                            </td>
                            <td>@log.RunBy</td>
                            <td><button id="detailBtn" class="cm-button-default-small" onclick="ShowDetail('@log.RequestJson','@log.ResponseJson')">Detail</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- The Modal -->
           <div id="detailModal" class="modal">
          <!-- Modal content -->
          <div class="modal-content">
            <span class="close" id="spanClose" onclick="closeModel()">&times;</span>
            <table border="1">
                <tr>
                    <td><b>Metered Event Request</b></td>
                    <td><span id="requestJson"></span></td>
                </tr>
                <tr>
                    <td><b>MarketPlace Response</b></td>
                    <td><span id="responseJson"></span></td>
                </tr>

            </table>
          </div>

        </div>
    </div>
    }
    else
    {
        <div>
            <h1><span class="cm-section-heading"> Please activate Scheduler feature to access this section</span></h1>
        </div>
    }
    </body>