src/AdminSite/Controllers/ApplicationConfigController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Marketplace.SaaS.Accelerator.DataAccess.Contracts;
using Marketplace.SaaS.Accelerator.DataAccess.Entities;
using Marketplace.SaaS.Accelerator.Services.Helpers;
using Marketplace.SaaS.Accelerator.Services.Services;
using Marketplace.SaaS.Accelerator.Services.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Marketplace.SaaS.Accelerator.AdminSite.Controllers;

/// <summary>
/// ApplicationConfig Controller.
/// </summary>
/// <seealso cref="BaseController" />
[ServiceFilter(typeof(KnownUserAttribute))]
[ServiceFilter(typeof(RequestLoggerActionFilter))]
public class ApplicationConfigController : BaseController
{
    private readonly SaaSClientLogger<ApplicationConfigController> logger;
    private readonly ApplicationConfigService appConfigService;

    /// <summary>
    /// Move to a new controller?
    /// </summary>
    private readonly IEmailTemplateRepository emailTemplateRepository;

    public ApplicationConfigController(IApplicationConfigRepository applicationConfigRepository,IEmailTemplateRepository emailTemplateRepository, SaaSClientLogger<ApplicationConfigController> logger) : base(applicationConfigRepository)
    {
        this.appConfigService = new ApplicationConfigService(applicationConfigRepository);
        this.emailTemplateRepository = emailTemplateRepository;
        this.logger = logger;
    }

    /// <summary>
    /// Main action for Application Config Page
    /// </summary>
    /// <returns>return All Application Config.</returns>
    [ServiceFilter(typeof(ExceptionHandlerAttribute))]
    public IActionResult Index()
    {
        var getAllAppConfigData = this.appConfigService.GetAllApplicationConfiguration();
        return this.View(getAllAppConfigData);
    }

    /// <summary>
    /// Indexes an EmailTemplate instance
    /// </summary>
    /// <returns>return a list of all EmailTemplates.</returns>
    [ServiceFilter(typeof(ExceptionHandlerAttribute))]
    public IActionResult EmailTemplates()
    {
        var getEmailTemplateData = this.emailTemplateRepository.GetAll();
        return this.View(getEmailTemplateData);
    }



    /// <summary>
    /// Get the fields of an EmailTemplate item by status
    /// </summary>
    /// <param name=status">The status that corresponds to the EmailTemplate.</param>
    /// <returns>
    /// return an EmailTemplate
    /// </returns>
    public IActionResult EmailTemplateDetails(string status)
    {
        var emailTemplate = this.emailTemplateRepository.GetTemplateForStatus(status);
        return this.PartialView(emailTemplate);
    }

    /// <summary>
    /// Saves changes to EmailTemplate
    /// </summary>
    /// <param name="emailTemplate">The modified EmailTemplate.</param>
    /// <returns>
    /// return the modified EmailTemplate.
    /// </returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult EmailTemplateDetails(EmailTemplate emailTemplate)
    {
        this.emailTemplateRepository.SaveEmailTemplateByStatus(emailTemplate);
        this.ModelState.Clear();
        return new OkResult();
    }



    /// <summary>
    /// Get the apllication config item by Id.
    /// </summary>
    /// <param name="Id">The app config Id.</param>
    /// <returns>
    /// return an Application Config item.
    /// </returns>
    public IActionResult ApplicationConfigDetails(int Id)
    {
        var applicationConfiguration = this.appConfigService.GetById(Id);
        return this.PartialView(applicationConfiguration);
    }


    /// <summary>
    /// Saves the app config item changes.
    /// </summary>
    /// <param name="appConfig">The app config item.</param>
    /// <returns>
    /// return the changed app config item.
    /// </returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult ApplicationConfigDetails(ApplicationConfiguration appConfig)
    {
        appConfig.Value = appConfig.Value ?? string.Empty;
        
        //check with the config is webhnotifcation url then validate if its proper url
        if (appConfig.Name == StringLiteralConstants.WebNotificationUrl && !UrlValidator.IsValidUrlHttps(appConfig.Value))
        {
            return this.BadRequest("Invalid URL, only https and port 443 are allowed.");
        }

        this.appConfigService.SaveAppConfig(appConfig);

        this.ModelState.Clear();
        return new OkResult();
    }


    /// <summary>
    /// Upload file(s) to database
    /// </summary>
    /// <param name="files">The files</param>
    /// <returns>RedirectToAction.</returns>
    [HttpPost("FileUpload")]
    [ServiceFilter(typeof(ExceptionHandlerAttribute))]
    [ValidateAntiForgeryToken]
    public IActionResult PostUpload(List<IFormFile> files)
    {
        if (!(files?.Any() == true))
        {
            TempData["Upload"] = "No files to upload";
            return RedirectToAction("Index");
        }
        if (files.Count > 2)
        {
            TempData["Upload"] = "No more than two files can be uploaded";
            return RedirectToAction("Index");
        }

        foreach (var file in files)
        {
            int maxLength = 1024 * 1024 * 5; //5 MB

            if (file.Length > maxLength)
            {
                TempData["Upload"] = "File is too large, max size of file for upload is 5 MB";
                return RedirectToAction("Index");
            }
            if (file.Length == 0)
            {
                TempData["Upload"] = "File is empty";
                return RedirectToAction("Index");
            }

            var fileExtension = Path.GetExtension(file.FileName).ToLowerInvariant();

            if (fileExtension != ".png" && fileExtension != ".ico")
            {
                TempData["Upload"] = "Only .png or .ico files can be uploaded";
                return RedirectToAction("Index");
            }

            var appConfigNames = this.appConfigService.GetAllApplicationConfiguration().Select(a => a.Name);

            if (!appConfigNames.Contains("LogoFile") || !appConfigNames.Contains("FaviconFile"))
            {
                TempData["Upload"] = "LogoFile or FaviconFile application config settings are missing in the database";
                return RedirectToAction("Index");
            }

            if (this.appConfigService.UploadFileToDatabase(file, fileExtension) == false)
            {
                TempData["Upload"] = "File Upload failed!";
                return RedirectToAction("Index");
            }
        }

        if (files.Count == 1)
        {
            TempData["Upload"] = files.FirstOrDefault().FileName + "  uploaded successfully";
        }
        else
        {
            TempData["Upload"] = files[0].FileName + " and " + files[1].FileName + " uploaded successfully";
        }

        return RedirectToAction("Index");
    }



}

src/AdminSite/Controllers/ApplicationLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Marketplace.SaaS.Accelerator.DataAccess.Contracts;
using Marketplace.SaaS.Accelerator.DataAccess.Entities;
using Marketplace.SaaS.Accelerator.Services.Services;
using Marketplace.SaaS.Accelerator.Services.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Marketplace.SaaS.Accelerator.AdminSite.Controllers;

[ServiceFilter(typeof(KnownUserAttribute))]
public class ApplicationLogController : BaseController
{
    private readonly SaaSClientLogger<ApplicationLogController> logger;

    private ApplicationLogService appLogService;

    private readonly IApplicationLogRepository appLogRepository;

    public ApplicationLogController(IApplicationLogRepository applicationLogRepository, SaaSClientLogger<ApplicationLogController> logger, IApplicationConfigRepository applicationConfigRepository):base(applicationConfigRepository)
    {
        this.appLogRepository = applicationLogRepository;
        this.logger = logger;
        appLogService = new ApplicationLogService(this.appLogRepository);
    }
    public IActionResult Index()
    {
        this.logger.Info("Application Log Controller / Index");
        try
        {
            List<ApplicationLog> getAllAppLogData = this.appLogService.GetAllLogs().OrderByDescending(appLog => appLog.ActionTime).ToList();
            getAllAppLogData.ForEach(s => s.LogDetail = Regex.Replace(s.LogDetail, "&quot;", "\""));
            return this.View(getAllAppLogData);
        }
        catch (Exception ex)
        {
            this.logger.LogError($"Message:{ex.Message} :: {ex.InnerException}");
            return this.View("Error", ex);
        }
    }


}

src/AdminSite/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
@model Marketplace.SaaS.Accelerator.DataAccess.Entities.ApplicationConfiguration


<div class="text-center mt20">
    <div class="card card-header">
        <dl class="row">
            <dt class="col-2 text-right"><span>Edit App Config</span></dt>
        </dl>
    </div>
    <form method="post" id="frmAppConfigDetails" asp-action="ApplicationConfigDetails" asp-controller="ApplicationConfig">
        <div>
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Name)
        </div>
        <table class="table table-bordered dt-responsive cm-table" id="tblcontainer">
            <theader>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Description</th>
                </tr>
            </theader>
            <tbody>
                <tr>
                    <td>
                        @Model.Name
                    </td>
                    <td>
                        @if (@Model.Name.Equals("SMTPPassword") && @Model?.Value?.Length > 5)
                        {
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { type ="password", @class = "form-control" } })
                        }
                        else
                        {
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                        }
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Description,new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="ac-save-d">
            <p>
                <a class="cm-button-default mt0" id="backButton"  asp-area="" asp-controller="ApplicationConfig" asp-action="Index">Back</a>
                <input class="cm-button-default mt0 ac-save-i" type="button" onclick="saveAppConfigDetails()" value="Save App Config" />
            </p>
        </div>
    </form>
</div>

<script>

    function saveAppConfigDetails() {
        var formobject = $('#frmAppConfigDetails').serialize();
        var csrftoken = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({
            url: 'ApplicationConfig/ApplicationConfigDetails',
            type: 'POST',
            headers: { RequestVerificationToken: csrftoken },
            data: formobject,
            cache: false,
            success: function (result) {
                swal({
                    title: "Saved",
                    text: "App config details saved successfully.",
                    icon: "success",
                    timer: 2000
                })
            },
            error:
                function (result) {
                    console.log();
                     swal({
                        title: "Error",
                        text: "An error has occured: "+ result.responseText,
                        icon: "error",
                        timer: 3000
                    })
                }
        });
    }

</script>

src/AdminSite/Views/ApplicationConfig/EmailTemplateDetails.cshtml
@model Marketplace.SaaS.Accelerator.DataAccess.Entities.EmailTemplate
<div class="text-center mt20">
    <div class="card card-header">
        <dl class="row">
            <dt class="col-2 text-right"><span>Edit Email Template</span></dt>
        </dl>
    </div>
    <form method="post" id="frmEmailTemplateDetails" asp-action="EmailTemplateDetails" asp-controller="ApplicationConfig">
        <div>
            @Html.HiddenFor(model => model.Status)
        </div>
        <div>
            @Html.HiddenFor(model => model.Id)
        </div>
        <table class="table table-bordered dt-responsive cm-table" id="tblcontainer">
            <theader>
                <tr>
                    <th class="text-start">Field</th>
                    <th class="text-start">Value</th>
                </tr>
            </theader>
            <tbody>
                <tr>
                    <td class="text-start">IsActive</td>
                    <td class="text-start">@Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { type ="checkbox", @class = "float-left", name="IsActive" } })</td>
                </tr>
                <tr>
                    <td class="text-start">Subject</td>
                    <td class="text-start">@Html.EditorFor(model => model.Subject, new { htmlAttributes = new {  @class = "form-control", name="Subject" } })</td>
                </tr>
                <tr>
                    <td class="text-start">Description</td>
                    <td class="text-start">@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", name="Description" } })</td>
                </tr>
                <tr>
                    <td class="text-start">TemplateBody</td>
                    <td class="text-start">
                        @Html.TextAreaFor(model => model.TemplateBody, new { @class = "form-control" })
                        <span class="fst-italic text-start">Due to the content size, it is recommended to copy the content to an external editor, modify the Template body, paste it back into here and save.</span>
                    </td>
                </tr>
                <tr>
                    <td class="text-start">ToRecipients</td>
                    <td class="text-start">@Html.EditorFor(model => model.ToRecipients, new { htmlAttributes = new { @class = "form-control", name="ToRecipients" } })</td>
                </tr>
                <tr>
                    <td class="text-start">Bcc</td>
                    <td class="text-start">@Html.EditorFor(model => model.Bcc, new { htmlAttributes = new { @class = "form-control", name="Bcc" } })</td>
                </tr>
                <tr>
                    <td class="text-start">Cc</td>
                    <td class="text-start">@Html.EditorFor(model => model.Cc, new { htmlAttributes = new { @class = "form-control", name="Cc" } })</td>
                </tr>
            </tbody>
        </table>
        <div class="ac-save-d">
            <p>
                <a class="cm-button-default mt0" id="backButton" style="text-decoration: none;" asp-area="" asp-controller="ApplicationConfig" asp-action="EmailTemplates">Back</a>
                <input class="cm-button-default mt0 ac-save-i" type="button" onclick="saveEmailTemplateDetails()" value="Save Template" />
            </p>
        </div>
    </form>
</div>

<script>

    function saveEmailTemplateDetails() {
        var formobject = $('#frmEmailTemplateDetails').serialize();
        var csrftoken = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({
            url: '/ApplicationConfig/EmailTemplateDetails',
            type: 'POST',
            headers: { RequestVerificationToken: csrftoken },
            data: formobject,
            cache: false,
            success: function (result) {
                debugger;
                swal({
                    title: "Saved",
                    text: "Email Template saved successfully.",
                    icon: "success",
                    timer: 1000
                });
            },
            Error:
                function (result) {
                    swal({
                        title: "Error",
                        text: "An error has occured, please check the log.",
                        icon: "error"
                    });
                }
        });
    }

</script>

src/AdminSite/Views/ApplicationConfig/EmailTemplates.cshtml
@model IEnumerable<Marketplace.SaaS.Accelerator.DataAccess.Entities.EmailTemplate>
@{
    ViewData["Title"] = "EmailTemplates";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <style>
        #dropdown02 {
            color: black;
        }
    </style>
<div class="container">
   <div class="card-body" style="margin-left:-30px;">
        <div class="text-left">
            <span class="cm-section-heading">Email Templates</span>
        </div>
          <div id="emailTemplatesModal">
                @if (Model != null && Model.Count() > 0)
                {
                     <div class="table-responsive mt20">
                         <table class="table table-bordered dt-responsive cm-table" width="100%" cellspacing="0">
                            <theader>
                                <tr>
                                    <th>ID</th>
                                    <th>Status</th>
                                    <th>Description</th>
                                    <th>IsActive</th>
                                    <th>Action</th>
                                </tr>
                            </theader>
                            <tbody>
                                @foreach (var template in Model)
                                {
                                    <tr>
                                        <td>
                                            @template.Id
                                        </td>
                                        <td>
                                            @template.Status
                                        </td>
                                        <td>
                                            @template.Description
                                        </td>
                                        <td>
                                            @template.IsActive
                                        </td>
                                        <td>
                                            <div class="nav-item dropdown minline">
                                                <a class="nav-link dropdown cm-link-button" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                                <div class="dropdown-menu" aria-labelledby="dropdown02">
                                                    <a class="dropdown-item cm-dropdown-option" data-bs-target="#emailTemplatesModal" onclick="ViewEmailTemplateDetailsByStatus('@template.Status')">Edit</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="ac-save-d">
                        <p>
                            <a class="cm-button-default mt0" id="backButton" style="text-decoration: none;" asp-area="" asp-controller="ApplicationConfig" asp-action="Index">Back</a>
                        </p>
                    </div>
                } else {

                    <div class="cm-panel-default mt40">
                        <div class="p-3 mr420">
                            <p>
                                You do not have any Email Templates
                            </p>
                        </div>
                    </div>

                }
        </div>
    </div>
</div>
</body>
<script>

    function ViewEmailTemplateDetailsByStatus(status) {
        $.ajax({
            type: "Get",
            url: "/ApplicationConfig/EmailTemplateDetails",
            data: { status },
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            success: function (data) {
                $('#emailTemplatesModal').html(data);
            },
            error: function () {
                 swal({
                        title: "Error",
                        text: "An error has occured, while loading details.",
                        icon: "error"
                    });
            }
        });
    }
   
   

</script>

src/AdminSite/Views/ApplicationConfig/Index.cshtml
@model IEnumerable<Marketplace.SaaS.Accelerator.DataAccess.Entities.ApplicationConfiguration>
@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <div class="">
        <div class="card-body admin-margin">
            <div class="text-left">
                <span class="cm-section-heading">Application Config</span>
            </div>
            <div id="myModal">
                <div class="table-responsive mt20">
                    <table class="table table-bordered dt-responsive cm-table" width="100%" cellspacing="0" id="applicationConfig">
                        <thead class="cm-table-head">
                            <tr>
                                <th>Config Name</th>
                                <th>Config Value</th>
                                <th>Config Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ var i = 0;}
                            @foreach (var item in Model)
                            {
                                @if (@item.Name.Equals("LogoFile") || @item.Name.Equals("FaviconFile")) continue;
                                <tr>
                                    <td class="text-left">
                                        @item.Name
                                    </td>
                                    <td class="text-left">
                                        @if (@item.Name.Equals("SMTPPassword") && @item?.Value?.Length > 5)
                                        {
                                            @String.Format("{0}{1}", @item.Value.Substring(0,5), "****************");
                                        }
                                        else
                                        {
                                            @item.Value
                                        }
                                    </td>
                                    <td class="text-left">
                                        @item.Description
                                    </td>
                                    <td class="cm-ellipsis">
                                        
                                        <a class="text-start nav-link dropdown cm-link-button" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                                            <a class="dropdown-item cm-dropdown-option" data-bs-target="#myModal" onclick="ViewAppConfigdetailsById('@item.Id')">Edit</a>
                                        </div>
                                       
                                    </td>
                                </tr>
                                i++;
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                <div>
                     <h2>Application Logs</h2>
                    <a class="cm-button-default mt0" style="text-decoration: none;" asp-area="" asp-controller="ApplicationLog" asp-action="Index">View Logs</a>
                </div>
                <br />
                <div>
                     <h2>Email Templates</h2>
                    <a class="cm-button-default mt0" style="text-decoration: none;" asp-area="" asp-controller="ApplicationConfig" asp-action="EmailTemplates">View Templates</a>
                </div>
                <br />
                <h2>Upload Logo</h2>
                <p style="font-size:10px;">*restart the application after uploading file(s) and refresh (ctrl F5) to see the new logo/favicon</p>
                <div class="row">
                    <section>
                        <form method="post" enctype="multipart/form-data"
                              asp-controller="FileUpload" asp-action="Index">
                            <div class="form-group">
                                <div class="col-md-auto">
                                    <input type="file" name="files" accept=".ico, .png" multiple />
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-md-auto">
                                    <input type="submit"  class="btn btn-primary" onclick="changeValue()" value="Upload" />
                                </div>
                            </div>
                        </form>
                    </section>
                </div>
                <label id="tempdataLabel">@TempData["Upload"]</label> 
            </div>
        </div>
    </div>
</div>
<script>
    function changeValue(){
        document.getElementById('tempdataLabel').innerHTML="In progress ..."    
    }

    function ViewAppConfigdetailsById(Id) {
            $.ajax({
                type: "Get",
                url: "ApplicationConfig/ApplicationConfigDetails",
                data: { Id: Id },
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    $('#myModal').html(data);
                },
                error: function () {
                    swal({
                        title: "Error",
                        text: "An error has occured, while loading details.",
                        icon: "error"
                    });
                }
            });
        }

</script>