src/AdminSite/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Web;
using Marketplace.SaaS.Accelerator.DataAccess.Contracts;
using Marketplace.SaaS.Accelerator.Services.Models;
using Marketplace.SaaS.Accelerator.Services.Services;
using Marketplace.SaaS.Accelerator.Services.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Marketplace.SaaS.Accelerator.AdminSite.Controllers;

/// <summary>
/// Plans Controller.
/// </summary>
/// <seealso cref="BaseController" />
[ServiceFilter(typeof(KnownUserAttribute))]
public class PlansController : BaseController
{
    /// <summary>
    /// The subscription repository.
    /// </summary>
    private readonly ISubscriptionsRepository subscriptionRepository;

    /// <summary>
    /// The users repository.
    /// </summary>
    private readonly IUsersRepository usersRepository;

    private readonly IApplicationConfigRepository applicationConfigRepository;

    private readonly IPlansRepository plansRepository;

    private readonly IOffersRepository offerRepository;

    private readonly IOfferAttributesRepository offerAttributeRepository;

    private readonly SaaSClientLogger<PlansController> logger;

    private PlanService plansService;

    /// <summary>
    /// Initializes a new instance of the <see cref="PlansController" /> class.
    /// </summary>
    /// <param name="subscriptionRepository">The subscription repository.</param>
    /// <param name="usersRepository">The users repository.</param>
    /// <param name="applicationConfigRepository">The application configuration repository.</param>
    /// <param name="plansRepository">The plans repository.</param>
    /// <param name="offerAttributeRepository">The offer attribute repository.</param>
    /// <param name="offerRepository">The offer repository.</param>
    /// <param name="logger">The logger.</param>
    public PlansController(ISubscriptionsRepository subscriptionRepository, IUsersRepository usersRepository, IApplicationConfigRepository applicationConfigRepository, IPlansRepository plansRepository, IOfferAttributesRepository offerAttributeRepository, IOffersRepository offerRepository, SaaSClientLogger<PlansController> logger):base(applicationConfigRepository)
    {
        this.subscriptionRepository = subscriptionRepository;
        this.usersRepository = usersRepository;
        this.applicationConfigRepository = applicationConfigRepository;
        this.plansRepository = plansRepository;
        this.offerAttributeRepository = offerAttributeRepository;
        this.offerRepository = offerRepository;
        this.logger = logger;
        this.plansService = new PlanService(this.plansRepository, this.offerAttributeRepository, this.offerRepository);
    }

    /// <summary>
    /// Indexes this instance.
    /// </summary>
    /// <returns>return All subscription.</returns>
    public IActionResult Index()
    {
        this.logger.Info("Plans Controller / OfferDetails:  offerGuId");
        try
        {
            List<PlansModel> getAllPlansData = new List<PlansModel>();
            this.TempData["ShowWelcomeScreen"] = "True";
            var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);


            getAllPlansData = this.plansService.GetPlans();

            return this.View(getAllPlansData);
        }
        catch (Exception ex)
        {
            this.logger.LogError($"Message:{ex.Message} :: {ex.InnerException}");
            return this.View("Error", ex);
        }
    }

    /// <summary>
    /// Indexes this instance.
    /// </summary>
    /// <param name="planGuId">The plan gu identifier.</param>
    /// <returns>
    /// return All subscription.
    /// </returns>
    public IActionResult PlanDetails(Guid planGuId)
    {
        this.logger.Info(HttpUtility.HtmlEncode($"Plans Controller / PlanDetails:  planGuId {planGuId}"));
        try
        {
            PlansModel plans = new PlansModel();
            this.TempData["ShowWelcomeScreen"] = "True";
            var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
            plans = this.plansService.GetPlanDetailByPlanGuId(planGuId);
            return this.PartialView(plans);
        }
        catch (Exception ex)
        {
            this.logger.LogError($"Message:{ex.Message} :: {ex.InnerException}");
            return this.View("Error", ex);
        }
    }

    /// <summary>
    /// Indexes this instance.
    /// </summary>
    /// <param name="plans">The plans.</param>
    /// <returns>
    /// return All subscription.
    /// </returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult PlanDetails(PlansModel plans)
    {
        this.logger.Info(HttpUtility.HtmlEncode($"Plans Controller / PlanDetails:  plans {JsonSerializer.Serialize(plans)}"));
        try
        {
            var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
            if (plans != null)
            {
                if (plans.PlanAttributes != null)
                {
                    var inputAtttributes = plans.PlanAttributes.Where(s => s.Type.ToLower() == "input").ToList();
                    foreach (var attributes in inputAtttributes)
                    {
                        attributes.UserId = currentUserDetail.UserId;
                        this.plansService.SavePlanAttributes(attributes);
                    }
                }

                if (plans.PlanEvents != null)
                {
                    foreach (var events in plans.PlanEvents)
                    {
                        events.UserId = currentUserDetail.UserId;
                        this.plansService.SavePlanEvents(events);
                    }
                }
            }

            this.ModelState.Clear();
            return this.RedirectToAction(nameof(this.PlanDetails), new { @planGuId = plans.PlanGUID });
        }
        catch (Exception ex)
        {
            this.logger.LogError($"Message:{ex.Message} :: {ex.InnerException}");
            return this.PartialView("Error", ex);
        }
    }


}

src/AdminSite/Views/Plans/Index.cshtml
@model List<Marketplace.SaaS.Accelerator.Services.Models.PlansModel>
@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <div class="">
        <div class="card-body">
            <div class="text-left">
                <span class="cm-section-heading">Plans</span>
            </div>

            <div id="myModal">
                
                @if (Model != null && Model.Count() > 0)
                {
                    <div class="table-responsive mt20">
                        <table class="table table-bordered dt-responsive cm-table text-start" width="100%" cellspacing="0">
                            <thead class="cm-table-head">
                                <tr>
                                    <th>Plan Name</th>
                                    <th>Description</th>
                                    <th>Offer</th>
                                    <th>Action</th>

                                </tr>
                            </thead>
                            <tbody class="text-start">
                                @{ var i = 0;}
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.DisplayName
                                        </td>
                                        <td>
                                            @item.Description
                                        </td>
                                        <td>
                                            @item.OfferName
                                        </td>
                                        <td class="cm-ellipsis">
                                            @* <div class="nav-item dropdown"> *@
                                            <a class="nav-link dropdown cm-link-button" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                                    <a class="dropdown-item cm-dropdown-option" data-bs-target="#myModal" onclick="ViewPlandetailsById('@item.PlanGUID')">Edit</a>
                                                </div>
                                            @* </div> *@
                                        </td>
                                    </tr>
                                    i++;
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {

                    <div class="cm-panel-default mt40">
                        <div class="p-3 mr420">
                            <p>
                                You do not have any Plans!
                            </p>
                        </div>
                    </div>

                }
          
            </div>
        </div>
    </div>
</div>


<script>
    function ViewPlandetailsById(PlanGUID) {
        $.ajax({
            type: "Get",
            url: "Plans/PlanDetails",
            data: { planGuId: PlanGUID },
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            success: function (data) {
                $('#myModal').html(data);
                //$('#myModal').modal();
            },
            error: function () {
                alert("Content load failed.");
            }
        });
    }
</script>

src/AdminSite/Views/Plans/PlanDetails.cshtml
@model Marketplace.SaaS.Accelerator.Services.Models.PlansModel
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .nav-tabs .nav-link {
            border: 1px solid #c5c5c5;
            background: #f6f6f6;
            font-weight: normal;
            color: #454545;
        }


        .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
            border: 1px solid #333;
            background: #333;
            font-weight: normal;
            color: #ffffff;
            margin-right: 0.2em;
        }

        .tabsborder {
            padding: .2em .2em 0;
            border: 1px solid #dddddd;
        }
    </style>
</head>
<body>

    <div class="card text-center mt20">
        <div class="card-header" style="background-color:#fff">
            <dl class="row">
                <dt class="col-2 text-end"><span>Offer Name</span></dt>
                <dd class="col-3 text-start">@Model.OfferName</dd>
                <dt class="col-3 text-end"><span>Plan name</span></dt>
                <dd class="col-4 text-start">@Model.DisplayName</dd>
            </dl>
        </div>

        <div class="card-body p-0">
            <form method="post" id="frmPlanEvents" asp-action="PlanDetails" asp-controller="Plans">
                <div>
                    @Html.HiddenFor(model => model.OfferID)
                    @Html.HiddenFor(model => model.PlanGUID)
                    @Html.HiddenFor(model => model.Id)
                </div>

                <ul class="nav nav-tabs m-0 tabsborder" role="tablist">
                    <li class="nav-item  mr-1"><a class="nav-link m-0 active" data-bs-toggle="tab" href="#tabs-Parameters">Parameters</a></li>
                    <li class="nav-item"><a class="nav-link m-0 " data-bs-toggle="tab" href="#tabs-Events">Events</a></li>
                </ul>

                <div class="tab-content">
                    <div class="container tab-pane container active" id="tabs-Parameters">
                        <br />
                        <div id="PlanAttributes">
                            @if (Model.PlanAttributes != null && Model.PlanAttributes.Count() > 0)
                            {
                                <table class="table table-bordered dt-responsive cm-table" id="tblcontainer">
                                    <theader>
                                        <tr>
                                            <th>DisplayName</th>
                                            <th>Enable</th>
                                        </tr>
                                    </theader>
                                    <tbody id="ReplacingTable" >
                                        @for (int i = 0; i < Model.PlanAttributes.Count(); i++)
                                        {


                                            <tr id="tr_PlanAttributes_@i" class="@Model.PlanAttributes[i].Type">
                                                <td>
                                                    <input id="PlanAttributes[@i].PlanAttributeId" type="hidden" value="@Model.PlanAttributes[i].PlanAttributeId" class="iHidden" name="PlanAttributes[@i].PlanAttributeId" />
                                                    <input id="PlanAttributes[@i].OfferAttributeId" type="hidden" value="@Model.PlanAttributes[i].OfferAttributeId" class="iHidden" name="PlanAttributes[@i].OfferAttributeId" />
                                                    <input id="PlanAttributes[@i].PlanId" type="hidden" value="@Model.PlanAttributes[i].PlanId" class="iHidden" name="PlanAttributes[@i].PlanId" />
                                                    <input id="PlanAttributes[@i].Type" type="hidden" value="@Model.PlanAttributes[i].Type" class="iHidden" name="PlanAttributes[@i].Type" />
                                                    @Model.PlanAttributes[i].DisplayName
                                                </td>
                                                <td>
                                                    @*<input type="checkbox" id="PlanAttributes[@i].IsEnabled" name="OfferAttributes[@i].IsEnabled" value="@Model.PlanAttributes[i].IsEnabled" />*@
                                                    @Html.CheckBoxFor(model => model.PlanAttributes[i].IsEnabled, new { name = "PlanAttributes[@i].IsEnabled", id = string.Format("PlanAttributes_IsEnabled_{0}", @i) })
                                                </td>
                                            </tr>


                                        }
                                    </tbody>
                                </table>
                            }
                            <div style="text-align:right;">
                                <p>
                                    <input class="cm-button-default mt0" type="button" style="background-color:#333" onclick="savePlanParameters()" value="Save Parameters" />
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="container tab-pane container fade" id="tabs-Events">
                        <br />
                        <div id="PlanEvents">
                            @if (Model.PlanEvents != null && Model.PlanEvents.Count() > 0)
                            {
                                <table class="table table-bordered dt-responsive cm-table" id="tblcontainer">
                                    <theader>
                                        <tr>
                                            <th>Event Name</th>
                                            <th>Active</th>
                                            <th>Copy To Customer</th>
                                            <th>
                                                Success Event Emails
                                            </th>
                                            <th>
                                                Failure Event Emails
                                            </th>
                                        </tr>
                                    </theader>
                                    <tbody id="ReplacingTable">
                                        @for (int i = 0; i < Model.PlanEvents.Count(); i++)
                                        {


                                            <tr id="tr_PlanEvents_@i">
                                                <td>
                                                    <input id="PlanEvents_Id_@i" type="hidden" value="@Model.PlanEvents[i].Id" class="iHidden" name="PlanEvents[@i].Id" />
                                                    <input id="PlanEvents_PlanId_@i" type="hidden" value="@Model.PlanEvents[i].PlanId" class="iHidden" name="PlanEvents[@i].PlanId" />
                                                    <input id="PlanEvents_EventId_@i" type="hidden" value="@Model.PlanEvents[i].EventId" class="iHidden" name="PlanEvents[@i].EventId" />
                                                    @*<input type="text" style="width:70px;" id="PlanAttributes[@i].DisplayName" name="PlanAttributes[@i].DisplayName" value="@Model.PlanAttributes[i].DisplayName" />*@
                                                    @Model.PlanEvents[i].EventName
                                                </td>
                                                <td>
                                                    @Html.CheckBoxFor(model => model.PlanEvents[i].Isactive, new { name = "PlanEvents[@i].Isactive", id = string.Format("PlanEvents_Isactive_{0}", @i) })
                                                    @*<input type="checkbox" id="PlanEvents_IsEnabled_@i" name="PlanEvents[@i].IsEnabled" value="@Model.PlanEvents[i].IsEnabled" />*@
                                                </td>
                                                <td>
                                                    @Html.CheckBoxFor(model => model.PlanEvents[i].CopyToCustomer, new { name = "PlanEvents[@i].CopyToCustomer", id = string.Format("PlanEvents_CopyToCustomer_{0}", @i) })
                                                    @*<input type="checkbox" id="PlanEvents_IsEnabled_@i" name="PlanEvents[@i].IsEnabled" value="@Model.PlanEvents[i].IsEnabled" />*@
                                                </td>
                                                <td><input type="text" style="width:200px;" id="PlanEvents_SuccessStateEmails_@i" name="PlanEvents[@i].SuccessStateEmails" value="@Model.PlanEvents[i].SuccessStateEmails" /></td>
                                                <td><input type="text" style="width:200px;" id="PlanEvents_FailureStateEmails_@i" name="PlanEvents[@i].FailureStateEmails" value="@Model.PlanEvents[i].FailureStateEmails" /></td>
                                            </tr>


                                        }
                                    </tbody>
                                </table>
                            }
                            <div style="text-align:right;">
                                <p>
                                    <input class="cm-button-default mt0" type="button" style="background-color:#333 " onclick="savePlanParameters()" value="Save Events" />
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>


</body>
<script>

    function successconfirmDialog() {
        swal({
            title: "Saved",
            text: "Plan parameters saved successfully.",
            icon: "success",
            timer: 1000
        })
    }
    function errorconfirmDialog() {
        swal({
            title: "Error",
            text: "An error has occured, please check the log.",
            icon: "error",
            timer: 1000
        })
    }
    function savePlanParameters() {
        var formobject = $('#frmPlanEvents').serialize();
        var csrftoken = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({
            url: 'Plans/PlanDetails',
            type: 'POST',
            headers: { RequestVerificationToken: csrftoken },
            data: formobject,
            cache: false,
            success: function (result) {
                debugger;
                successconfirmDialog();
                $('#myModal').html(result);
            },
            Error:
                function (result) {
                    errorconfirmDialog();
                    $('#myModal').html(result);
                }
        });
    }

</script>

src/AdminSite/Views/Plans/SuccessMessage.cshtml
@*@using Microsoft.Marketplace.SaasKit.Client.Models*@
@using Microsoft.AspNetCore.Mvc.TagHelpers
@*@model Microsoft.Marketplace.SaasKit.Client.Models.SubscriptionResultExtensionSubscriptionResultExtension
    @{
        //ViewData["Title"] = "Home";
    }*@
<div class="container">
    <form method="post">
        <div class="cm-panel-default mt40">
            <div class="p-3">
                <p>
                    Plan parameters updated successfully.
                </p>
            </div>
        </div>
        <div class="text-right">
            <button type="submit" asp-action="Index" asp-controller="Plans" class="cm-button-default mt40 text-end">Go to Subscription List</button>
        </div>
    </form>
</div>